In [2]:
# Load the dataset
import pandas as pd
data=pd.read_csv('all_kindle_review.csv')
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [3]:
df=data[['reviewText','rating']]
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [4]:
## Missing Values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [5]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [6]:
## postive review is 1 and negative review is 0
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

C:\Users\ARINDAM CHOUDHURY\AppData\Local\Temp\ipykernel_10268\3208188810.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)


In [7]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [8]:
## 1. Lower All the cases
df['reviewText']=df['reviewText'].str.lower()

C:\Users\ARINDAM CHOUDHURY\AppData\Local\Temp\ipykernel_10268\1654308119.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].str.lower()


In [9]:
df.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [10]:
pip install nltk


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\ARINDAM
[nltk_data]     CHOUDHURY\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
pip install bs4

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
from bs4 import BeautifulSoup

In [14]:
pip install lxml


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [17]:


# Load stopwords once
stop_words = set(stopwords.words('english'))

# Precompile regex
regex_non_alpha = re.compile('[^a-zA-Z0-9- ]+')
regex_url = re.compile(r'(http|https|ftp|ssh)://\S+')

# Remove special characters
df.loc[:, 'reviewText'] = df['reviewText'].apply(lambda x: regex_non_alpha.sub(' ', str(x)))

# Remove stopwords
df.loc[:, 'reviewText'] = df['reviewText'].apply(lambda x: " ".join([y for y in x.split() if y.lower() not in stop_words]))

# Remove URLs
df.loc[:, 'reviewText'] = df['reviewText'].apply(lambda x: regex_url.sub('', str(x)))

# Remove HTML tags
df.loc[:, 'reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(str(x), 'lxml').get_text())

# Remove extra spaces
df.loc[:, 'reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))


In [22]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer

In [23]:
lemmatizer=WordNetLemmatizer()

In [24]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])


In [26]:
import nltk
nltk.download('wordnet')


[nltk_data] Downloading package wordnet to C:\Users\ARINDAM
[nltk_data]     CHOUDHURY\AppData\Roaming\nltk_data...


True

In [27]:
df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))

C:\Users\ARINDAM CHOUDHURY\AppData\Local\Temp\ipykernel_10268\1959687590.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText']=df['reviewText'].apply(lambda x:lemmatize_words(x))


In [28]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['reviewText'],df['rating'],
                                              test_size=0.20)

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [39]:
pip install gensim


   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
    --------------------------------------- 0.5/24.4 MB 5.6 MB/s eta 0:00:05
   --- ------------------------------------ 1.8/24.4 MB 6.3 MB/s eta 0:00:04
   ---- ----------------------------------- 2.6/24.4 MB 6.0 MB/s eta 0:00:04
   ----- ---------------------------------- 3.1/24.4 MB 4.3 MB/s eta 0:00:05
   ------- -------------------------------- 4.5/24.4 MB 4.8 MB/s eta 0:00:05
   --------- ------------------------------ 5.8/24.4 MB 5.0 MB/s eta 0:00:04
   --------- ------------------------------ 5.8/24.4 MB 5.0 MB/s eta 0:00:04
   ----------- ---------------------------- 7.1/24.4 MB 4.5 MB/s eta 0:00:04
   ------------- -------------------------- 8.4/24.4 MB 4.8 MB/s eta 0:00:04
   --------------- ------------------------ 9.4/24.4 MB 5.0 MB/s eta 0:00:04
   ---------------- ----------------------- 10.2/24.4 MB 4.7 MB/s eta 0:00:04
   ------------------- -------------------- 11.8/24.4 MB 4.9 MB/s eta 0:00:03
   -


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [40]:
# Assuming your reviews are lemmatized
X_train_tokens = [review.split() for review in X_train]  # train reviews
X_test_tokens = [review.split() for review in X_test]    # test reviews


In [41]:
from gensim.models import Word2Vec

# Train on your training data
w2v_model = Word2Vec(
    sentences=X_train_tokens,  # tokenized sentences
    vector_size=100,           # dimension of embeddings
    window=5,                  # context window
    min_count=1,               # ignore words with freq < 1
    workers=4                  # parallel threads
)


In [42]:
import numpy as np

def get_average_word2vec(tokens, model, vector_size):
    vec = np.zeros(vector_size)  # initialize zero vector
    count = 0
    for word in tokens:
        if word in model.wv:     # check if word is in vocab
            vec += model.wv[word]
            count += 1
    if count != 0:
        vec /= count              # average
    return vec


In [43]:
vector_size = 100  # same as in Word2Vec

X_train_w2v = np.array([get_average_word2vec(tokens, w2v_model, vector_size) for tokens in X_train_tokens])
X_test_w2v = np.array([get_average_word2vec(tokens, w2v_model, vector_size) for tokens in X_test_tokens])


In [31]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [33]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

In [34]:
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [35]:
confusion_matrix(y_test,y_pred_bow)

array([[544, 265],
       [746, 845]])

In [36]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.57875


In [37]:
confusion_matrix(y_test,y_pred_tfidf)

array([[533, 276],
       [744, 847]])

In [38]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.575
